# Generated by Django 3.2 on 2021-04-19 02:55

from django.db import migrations, models
import pages.validadores


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=20, validators=[pages.validadores.validarMayusculas, pages.validadores.validarNE], verbose_name='Primer Nombre')),
                ('nombre2', models.CharField(max_length=50, validators=[pages.validadores.validarMayusculas, pages.validadores.validarNE], verbose_name='Primer Nombre')),
                ('apellido1', models.CharField(max_length=20, validators=[pages.validadores.validarMayusculas, pages.validadores.validarNE], verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(max_length=20, validators=[pages.validadores.validarMayusculas, pages.validadores.validarNE], verbose_name='Segundo Apellido')),
                ('pais', models.CharField(choices=[('CO', 'Colombia'), ('US', 'Estados Unidos')], default='CO', max_length=2)),
                ('tipoId', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CEXT', 'Cédula de Extranjería'), ('PASSP', 'Pasaporte'), ('PER_ESP', 'Permiso Especial')], default='CC', max_length=7)),
                ('numeroId', models.CharField(max_length=20, validators=[pages.validadores.validarIdentificacion], verbose_name='-\tNúmero de Identificación')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('order', models.SmallIntegerField(default=0, verbose_name='Orden')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['order', 'nombre1'],
            },
        ),
    ]
