# Generated by Django 3.2 on 2021-04-19 00:10

from django.db import migrations, models
import pages.validadores


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='nombre1',
            field=models.CharField(max_length=200, validators=[pages.validadores.validarMayusculas], verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='page',
            name='nombre2',
            field=models.CharField(max_length=200, validators=[pages.validadores.validarMayusculas], verbose_name='Primer Nombre'),
        ),
    ]
