# Generated by Django 3.2 on 2021-04-19 00:58

import ckeditor.fields
from django.db import migrations
import pages.validadores


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210418_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='nombre2',
            field=ckeditor.fields.RichTextField(max_length=200, validators=[pages.validadores.validarMayusculas], verbose_name='Segundo Nombre'),
        ),
    ]
